//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.26 at 03:55:58 PM CEST 
//


package firma.presek;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the firma.presek package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StavkaPreseka_QNAME = new QName("http://firma/presek", "stavkaPreseka");
    private final static QName _ZaglavljePreseka_QNAME = new QName("http://firma/presek", "zaglavljePreseka");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: firma.presek
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StavkaPreseka }
     * 
     */
    public StavkaPreseka createStavkaPreseka() {
        return new StavkaPreseka();
    }

    /**
     * Create an instance of {@link GetPresekRequest }
     * 
     */
    public GetPresekRequest createGetPresekRequest() {
        return new GetPresekRequest();
    }

    /**
     * Create an instance of {@link Presek }
     * 
     */
    public Presek createPresek() {
        return new Presek();
    }

    /**
     * Create an instance of {@link ZaglavljePreseka }
     * 
     */
    public ZaglavljePreseka createZaglavljePreseka() {
        return new ZaglavljePreseka();
    }

    /**
     * Create an instance of {@link GetPresekResponse }
     * 
     */
    public GetPresekResponse createGetPresekResponse() {
        return new GetPresekResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StavkaPreseka }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://firma/presek", name = "stavkaPreseka")
    public JAXBElement<StavkaPreseka> createStavkaPreseka(StavkaPreseka value) {
        return new JAXBElement<StavkaPreseka>(_StavkaPreseka_QNAME, StavkaPreseka.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZaglavljePreseka }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://firma/presek", name = "zaglavljePreseka")
    public JAXBElement<ZaglavljePreseka> createZaglavljePreseka(ZaglavljePreseka value) {
        return new JAXBElement<ZaglavljePreseka>(_ZaglavljePreseka_QNAME, ZaglavljePreseka.class, null, value);
    }

}
